// Generated with carray.sh from /home/biancaa/boot_test/opensbi/lib/utils/ipi/fdt_ipi_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/ipi/fdt_ipi.h>


const struct fdt_driver *const fdt_ipi_drivers[] = {
	NULL
};
