// Generated with carray.sh from /home/biancaa/boot_test/opensbi/lib/utils/serial/fdt_serial_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/serial/fdt_serial.h>

extern const struct fdt_driver fdt_serial_mindgrove;

const struct fdt_driver *const fdt_serial_drivers[] = {
	&fdt_serial_mindgrove,
	NULL
};
