// Generated with carray.sh from /home/biancaa/boot_test/opensbi/lib/utils/irqchip/fdt_irqchip_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/irqchip/fdt_irqchip.h>

extern const struct fdt_driver fdt_irqchip_plic;

const struct fdt_driver *const fdt_irqchip_drivers[] = {
	&fdt_irqchip_plic,
	NULL
};
