// Generated with carray.sh from /home/biancaa/boot_test/opensbi/platform/generic/platform_override_modules.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <platform_override.h>

extern const struct fdt_driver thead_generic;
extern const struct fdt_driver starfive_jh7110;
extern const struct fdt_driver sophgo_sg2042;
extern const struct fdt_driver sifive_fu540;
extern const struct fdt_driver sifive_fu740;
extern const struct fdt_driver renesas_rzfive;
extern const struct fdt_driver mips_p8700;
extern const struct fdt_driver andes_ae350;
extern const struct fdt_driver sun20i_d1;

const struct fdt_driver *const platform_override_modules[] = {
	&thead_generic,
	&starfive_jh7110,
	&sophgo_sg2042,
	&sifive_fu540,
	&sifive_fu740,
	&renesas_rzfive,
	&mips_p8700,
	&andes_ae350,
	&sun20i_d1,
	NULL
};
