// Generated with carray.sh from /home/biancaa/boot_test/opensbi/lib/utils/fdt/fdt_early_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/fdt/fdt_driver.h>


const struct fdt_driver *const fdt_early_drivers[] = {
	NULL
};
