// Generated with carray.sh from /home/biancaa/boot_test/opensbi/platform/generic/platform_override_modules.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <platform_override.h>


const struct fdt_driver *const platform_override_modules[] = {
	NULL
};
